# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       detox

# >> macros
# << macros

Summary:    a program that renames files to make them easier to work with
Version:    1.4.5
Release:    0
Group:      System
License:    BSD-3-Clause
URL:        https://github.com/dharple/detox
Source0:    %{name}-%{version}.tar.gz
Source100:  detox.yaml
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  bison
BuildRequires:  flex

%description
%{summary}
under Unix and related operating systems.  

Spaces and various other unsafe characters (such as "$") get replaced with
"_". ISO 8859-1 (Latin-1) characters can be transliterated to ASCII, as can
UTF-8 characters.

%if "%{?vendor}" == "chum"
PackageName: Detox
PackagerName: nephros
Type: console-application
Categories:
  - Utility
  - FileTools
Custom:
  PackagingRepo: https://github.com/sailfishos-chum/detox
%endif


%package doc
Summary:    Documentation for %{name}
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
%{summary}.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    CFLAGS="$RPM_OPT_FLAGS -fPIC -pie" \
    CXXFLAGS="$RPM_OPT_FLAGS -fPIC -pie"

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%license LICENSE
%{_bindir}/*
%config(noreplace) %{_sysconfdir}/detoxrc
%config %{_sysconfdir}/detoxrc.sample
%{_datadir}/%{name}/iso8859_1.tbl
%{_datadir}/%{name}/iso8859_1.tbl.sample
%{_datadir}/%{name}/safe.tbl
%{_datadir}/%{name}/safe.tbl.sample
%{_datadir}/%{name}/unicode.tbl
%{_datadir}/%{name}/unicode.tbl.sample
%doc %{_docdir}/detox/README.md
# >> files
# << files

%files doc
%defattr(-,root,root,-)
%{_mandir}/*/*
# >> files doc
# << files doc
